/*
Hindsight HTTP API

Testing OperationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_OperationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OperationsAPIService CancelOperation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var operationId string

		resp, httpRes, err := apiClient.OperationsAPI.CancelOperation(context.Background(), bankId, operationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationsAPIService GetOperationStatus", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var operationId string

		resp, httpRes, err := apiClient.OperationsAPI.GetOperationStatus(context.Background(), bankId, operationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationsAPIService ListOperations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.OperationsAPI.ListOperations(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
