/*
Hindsight HTTP API

Testing DocumentsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_DocumentsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DocumentsAPIService DeleteDocument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var documentId string

		resp, httpRes, err := apiClient.DocumentsAPI.DeleteDocument(context.Background(), bankId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DocumentsAPIService GetChunk", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var chunkId string

		resp, httpRes, err := apiClient.DocumentsAPI.GetChunk(context.Background(), chunkId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DocumentsAPIService GetDocument", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var documentId string

		resp, httpRes, err := apiClient.DocumentsAPI.GetDocument(context.Background(), bankId, documentId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DocumentsAPIService ListDocuments", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.DocumentsAPI.ListDocuments(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
