/*
Hindsight HTTP API

Testing MemoryAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_MemoryAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MemoryAPIService ClearBankMemories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.ClearBankMemories(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService GetGraph", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.GetGraph(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService GetMemory", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var memoryId string

		resp, httpRes, err := apiClient.MemoryAPI.GetMemory(context.Background(), bankId, memoryId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService ListMemories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.ListMemories(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService ListTags", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.ListTags(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService RecallMemories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.RecallMemories(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService Reflect", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.Reflect(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MemoryAPIService RetainMemories", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MemoryAPI.RetainMemories(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
