/*
Hindsight HTTP API

Testing DirectivesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_DirectivesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DirectivesAPIService CreateDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.DirectivesAPI.CreateDirective(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService DeleteDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.DeleteDirective(context.Background(), bankId, directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService GetDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.GetDirective(context.Background(), bankId, directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService ListDirectives", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.DirectivesAPI.ListDirectives(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DirectivesAPIService UpdateDirective", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var directiveId string

		resp, httpRes, err := apiClient.DirectivesAPI.UpdateDirective(context.Background(), bankId, directiveId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
