/*
Hindsight HTTP API

Testing BanksAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_BanksAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BanksAPIService AddBankBackground", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.AddBankBackground(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService ClearObservations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.ClearObservations(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService CreateOrUpdateBank", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.CreateOrUpdateBank(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService DeleteBank", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.DeleteBank(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService GetAgentStats", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.GetAgentStats(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService GetBankConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.GetBankConfig(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService GetBankProfile", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.GetBankProfile(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService ListBanks", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BanksAPI.ListBanks(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService ResetBankConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.ResetBankConfig(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService TriggerConsolidation", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.TriggerConsolidation(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService UpdateBank", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.UpdateBank(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService UpdateBankConfig", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.UpdateBankConfig(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BanksAPIService UpdateBankDisposition", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.BanksAPI.UpdateBankDisposition(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
