/*
Hindsight HTTP API

Testing EntitiesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_EntitiesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EntitiesAPIService GetEntity", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var entityId string

		resp, httpRes, err := apiClient.EntitiesAPI.GetEntity(context.Background(), bankId, entityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitiesAPIService ListEntities", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.EntitiesAPI.ListEntities(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test EntitiesAPIService RegenerateEntityObservations", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var entityId string

		resp, httpRes, err := apiClient.EntitiesAPI.RegenerateEntityObservations(context.Background(), bankId, entityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
