/*
Hindsight HTTP API

Testing MentalModelsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package hindsight

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vectorize-io/hindsight/hindsight-clients/go"
)

func Test_hindsight_MentalModelsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MentalModelsAPIService CreateMentalModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MentalModelsAPI.CreateMentalModel(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MentalModelsAPIService DeleteMentalModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var mentalModelId string

		resp, httpRes, err := apiClient.MentalModelsAPI.DeleteMentalModel(context.Background(), bankId, mentalModelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MentalModelsAPIService GetMentalModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var mentalModelId string

		resp, httpRes, err := apiClient.MentalModelsAPI.GetMentalModel(context.Background(), bankId, mentalModelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MentalModelsAPIService ListMentalModels", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string

		resp, httpRes, err := apiClient.MentalModelsAPI.ListMentalModels(context.Background(), bankId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MentalModelsAPIService RefreshMentalModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var mentalModelId string

		resp, httpRes, err := apiClient.MentalModelsAPI.RefreshMentalModel(context.Background(), bankId, mentalModelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test MentalModelsAPIService UpdateMentalModel", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var bankId string
		var mentalModelId string

		resp, httpRes, err := apiClient.MentalModelsAPI.UpdateMentalModel(context.Background(), bankId, mentalModelId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
