fp = 'CompanionChat/app/src/main/java/com/companion/chat/locale/Strings.kt'
with open(fp, 'r', encoding='utf-8') as f:
    c = f.read()

# ZH translations - insert after discover_import_failed
zh = '''        StringsKey.discover_image_generated to "图片已生成: %s",
        StringsKey.voice_recognition_mode to "识别模式",
        StringsKey.voice_recognition_backend to "识别后端",
        StringsKey.voice_model_directory to "模型目录",
        StringsKey.voice_model_status to "模型状态",
        StringsKey.voice_cloud_asr_label to "云 ASR",
        StringsKey.voice_cloud_response_field to "云响应字段",
        StringsKey.voice_moss_directory to "MOSS 目录",
        StringsKey.voice_moss_status to "MOSS 状态",
        StringsKey.voice_local_clone to "本地克隆",
        StringsKey.voice_output_mode to "输出模式",
        StringsKey.voice_default_timbre to "默认音色",
        StringsKey.voice_role_voice to "角色语音",
        StringsKey.voice_not_configured to "未配置",
        StringsKey.voice_configured to "已配置",
        StringsKey.voice_local_sensevoice to "本地 SenseVoice ASR",
        StringsKey.voice_cloud_http_asr to "云 HTTP ASR",
        StringsKey.voice_moss_nano_default to "MOSS TTS Nano（默认引擎）",
        StringsKey.voice_fallback_tts to "回退系统 TTS",
        StringsKey.voice_clone_default to "MOSS 本地克隆（默认）",
        StringsKey.voice_role_voice_hint to "在角色管理中配置参考音频 URI、模式和显示名称",
        StringsKey.voice_desc to "语音输入默认使用本地 SenseVoice。默认使用 moss-tts-nano ONNX 模型进行语音克隆，缺模型或缺参考音频时自动回退系统 TTS。",
        StringsKey.voice_auto_read_desc to "AI 开始回复 0.5 秒后，按句子自动朗读",
        StringsKey.voice_ready to "完整",
        StringsKey.voice_local_not_configured to "本地 SenseVoice 模型未配置",
        StringsKey.voice_moss_not_configured to "moss-tts-nano 模型未配置",
        StringsKey.voice_invalid_config to "配置无效：%s",
        StringsKey.voice_missing_files to "文件缺失：%s",
        StringsKey.home_discover to "发现",
        StringsKey.home_sort to "排序",
        StringsKey.home_sort_hot to "热门",
        StringsKey.home_sort_newest to "最新",
        StringsKey.home_sort_name to "名称",
        StringsKey.home_search_hint to "搜索角色、作者、标签",
        StringsKey.home_create_your_role to "创建你的角色",
        StringsKey.home_create_hint to "人设、头像、语音会保存到角色卡",
        StringsKey.home_create to "创建",
        StringsKey.home_show_mature to "显示私密",
        StringsKey.home_role_detail to "角色详情",
        StringsKey.home_not_found to "未找到角色",
        StringsKey.home_by_author to "by %s",
        StringsKey.home_imported to "已导入",
        StringsKey.home_unlocked to "已解锁",
        StringsKey.home_start_chat_btn to "开始聊天",
        StringsKey.home_unlock_to_favorite to "收藏解锁",
        StringsKey.home_generating to "生成中",
        StringsKey.home_generate_image to "生成图片",
        StringsKey.home_edit_character to "编辑角色卡",
        StringsKey.home_mature_label to "私密",
        StringsKey.chat_quick_continue to "继续聊聊",
        StringsKey.chat_quick_generate_img to "生成此刻图片",
        StringsKey.char_mgmt_persona_label to "人设：%s",
        StringsKey.char_mgmt_style_label to "风格：%s",
        StringsKey.char_mgmt_image_label to "图片：头像%s，图库 %d 张",
        StringsKey.char_mgmt_voice_label to "语音：%s",
        StringsKey.char_mgmt_avatar_configured to "已配置",
        StringsKey.char_mgmt_avatar_missing to "未配置",
        StringsKey.skills_used_count to "已使用 %d 次",
        StringsKey.skills_delete_confirm to "确认删除"%s"吗？",
        StringsKey.detail_persona to "人设摘要",
        StringsKey.detail_voice to "语音",
        StringsKey.detail_image_style to "图片风格",
        StringsKey.voice_policy_no_text'''

c = c.replace(
    'StringsKey.discover_image_generated to "图片已生成: %s",\n        StringsKey.voice_policy_no_text',
    zh
)

with open(fp, 'w', encoding='utf-8') as f:
    f.write(c)
print("Stage 2: ZH translations added")
