fp = 'CompanionChat/app/src/main/java/com/companion/chat/locale/Strings.kt'
with open(fp, 'r', encoding='utf-8') as f:
    c = f.read()

en = '''        StringsKey.discover_image_generated to "Image generated: %s",
        StringsKey.voice_recognition_mode to "Recognition mode",
        StringsKey.voice_recognition_backend to "Recognition backend",
        StringsKey.voice_model_directory to "Model directory",
        StringsKey.voice_model_status to "Model status",
        StringsKey.voice_cloud_asr_label to "Cloud ASR",
        StringsKey.voice_cloud_response_field to "Cloud response field",
        StringsKey.voice_moss_directory to "MOSS directory",
        StringsKey.voice_moss_status to "MOSS status",
        StringsKey.voice_local_clone to "Local clone",
        StringsKey.voice_output_mode to "Output mode",
        StringsKey.voice_default_timbre to "Default voice",
        StringsKey.voice_role_voice to "Character voice",
        StringsKey.voice_not_configured to "Not configured",
        StringsKey.voice_configured to "Configured",
        StringsKey.voice_local_sensevoice to "Local SenseVoice ASR",
        StringsKey.voice_cloud_http_asr to "Cloud HTTP ASR",
        StringsKey.voice_moss_nano_default to "MOSS TTS Nano (default engine)",
        StringsKey.voice_fallback_tts to "Fallback to system TTS",
        StringsKey.voice_clone_default to "MOSS local clone (default)",
        StringsKey.voice_role_voice_hint to "Configure reference audio URI, mode and display name in character management",
        StringsKey.voice_desc to "Voice input uses local SenseVoice by default. Uses moss-tts-nano ONNX model for voice cloning, falls back to system TTS when model or reference audio is missing.",
        StringsKey.voice_auto_read_desc to "Auto-read by sentence 0.5s after AI starts replying",
        StringsKey.voice_ready to "Complete",
        StringsKey.voice_local_not_configured to "Local SenseVoice model not configured",
        StringsKey.voice_moss_not_configured to "moss-tts-nano model not configured",
        StringsKey.voice_invalid_config to "Invalid config: %s",
        StringsKey.voice_missing_files to "Missing files: %s",
        StringsKey.home_discover to "Discover",
        StringsKey.home_sort to "Sort",
        StringsKey.home_sort_hot to "Hot",
        StringsKey.home_sort_newest to "Newest",
        StringsKey.home_sort_name to "Name",
        StringsKey.home_search_hint to "Search characters, authors, tags",
        StringsKey.home_create_your_role to "Create your character",
        StringsKey.home_create_hint to "Persona, avatar, voice saved to character card",
        StringsKey.home_create to "Create",
        StringsKey.home_show_mature to "Show mature",
        StringsKey.home_role_detail to "Character details",
        StringsKey.home_not_found to "Character not found",
        StringsKey.home_by_author to "by %s",
        StringsKey.home_imported to "Imported",
        StringsKey.home_unlocked to "Unlocked",
        StringsKey.home_start_chat_btn to "Start chat",
        StringsKey.home_unlock_to_favorite to "Unlock to favorite",
        StringsKey.home_generating to "Generating",
        StringsKey.home_generate_image to "Generate image",
        StringsKey.home_edit_character to "Edit character card",
        StringsKey.home_mature_label to "Mature",
        StringsKey.chat_quick_continue to "Continue chatting",
        StringsKey.chat_quick_generate_img to "Generate scene image",
        StringsKey.char_mgmt_persona_label to "Persona: %s",
        StringsKey.char_mgmt_style_label to "Style: %s",
        StringsKey.char_mgmt_image_label to "Image: avatar %s, gallery %d images",
        StringsKey.char_mgmt_voice_label to "Voice: %s",
        StringsKey.char_mgmt_avatar_configured to "configured",
        StringsKey.char_mgmt_avatar_missing to "not configured",
        StringsKey.skills_used_count to "Used %d times",
        StringsKey.skills_delete_confirm to 'Delete "%s"?',
        StringsKey.detail_persona to "Persona summary",
        StringsKey.detail_voice to "Voice",
        StringsKey.detail_image_style to "Image style",
        StringsKey.voice_policy_no_text'''

c = c.replace(
    'StringsKey.discover_image_generated to "Image generated: %s",\n        StringsKey.voice_policy_no_text',
    en
)

with open(fp, 'w', encoding='utf-8') as f:
    f.write(c)
print("Stage 3: EN translations added")
