"""Render the structured memory store into memU's markdown "memory file system".

The exporter projects the (optionally scoped) store into the navigable file tree
described in the README:

    <output_dir>/
    ├── INDEX.md                     ← index of the raw files under resource/
    ├── MEMORY.md                    ← overall overview + index of memory/
    ├── SKILL.md                     ← index of the skills under skill/
    ├── resource/
    │   └── <file_name>              ← one copied raw source file
    ├── memory/
    │   └── <slug>.md                ← one memory category (description + summary)
    └── skill/
        └── <skill_name>/SKILL.md    ← one synthesized skill per folder

Each artifact is a different aggregation of what the agent has stored. The three
root indexes (``INDEX.md`` / ``MEMORY.md`` / ``SKILL.md``) each point at a sibling
directory of payloads (``resource/`` / ``memory/`` / ``skill/``):

- ``resource/`` : the raw source files copied verbatim out of the blob store
  (``Resource.local_path``), so the actual ingested bytes live next to the memory.
- ``INDEX.md``  : an index of those raw files (name, modality, description, link
  into ``resource/``), so an agent knows which raw resources exist.
- ``memory/``   : the living memory split one file per
  :class:`~memu.database.models.MemoryCategory` (its description + summary).
- ``MEMORY.md`` : an overall overview that links to each ``memory/<slug>.md`` file.
- ``skill/**``  : reusable skills synthesized from the per-source descriptions (a
  sibling of ``MEMORY.md``, never derived from extracted skill-type memory items);
  the synthesized ``slug -> body`` map is supplied by the caller.
- ``SKILL.md`` (root): a generated index/table of contents over the ``skill/`` tree.

This layer is read-only against the database and never mutates memory records.
A sidecar manifest (``.memufs_manifest.json``) records the content hash of every
artifact this exporter owns, so each export only rewrites files whose rendered
content actually changed (diff detection) — no database schema change required.
Rendered content avoids volatile values (e.g. "now" timestamps) so re-exporting
an unchanged store is detected as a no-op.
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import re
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from memu.database.interfaces import Database
    from memu.database.models import MemoryCategory, MemoryItem, Resource

MANIFEST_NAME = ".memufs_manifest.json"
SKILL_DIRNAME = "skill"
RESOURCE_DIRNAME = "resource"
MEMORY_DIRNAME = "memory"
SKILL_FILENAME = "SKILL.md"
SKILL_INDEX_FILENAME = "SKILL.md"
INDEX_FILENAME = "INDEX.md"
MEMORY_FILENAME = "MEMORY.md"
_GENERATED_NOTICE = "<!-- Auto-generated by memU memory_fs. Do not edit by hand. -->"


@dataclass
class FileDescription:
    """A single source file's multimodal description (the shared trunk).

    Derived from a :class:`~memu.database.models.Resource`: ``caption`` is the
    text/caption produced by preprocessing, regardless of original modality.
    ``local_path`` points at the ingested file inside the resources dir.
    """

    url: str
    modality: str
    description: str
    resource_id: str
    local_path: str = ""

    @property
    def file_name(self) -> str:
        """The ingested file's name in the resources dir (fallback: the url)."""
        name = pathlib.Path(self.local_path).name if self.local_path else ""
        return name or self.url


@dataclass
class ExportResult:
    """Outcome of a single export pass."""

    output_dir: str
    written: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    removed: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.written or self.removed)

    def to_dict(self) -> dict[str, Any]:
        return {
            "output_dir": self.output_dir,
            "changed": self.changed,
            "written": sorted(self.written),
            "unchanged": sorted(self.unchanged),
            "removed": sorted(self.removed),
        }


def slugify(name: str) -> str:
    """Turn a name into a filesystem-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "untitled"


def _content_hash(content: str | bytes) -> str:
    data = content if isinstance(content, bytes) else content.encode("utf-8")
    return hashlib.sha256(data).hexdigest()


class MemoryFileExporter:
    """Render a :class:`~memu.database.interfaces.Database` into the markdown tree.

    The exporter is stateless apart from the on-disk manifest, so a single
    instance can be reused across scopes/exports. Callers are responsible for
    serializing concurrent exports that target the same ``output_dir``.
    """

    def __init__(self, output_dir: str) -> None:
        self.output_dir = pathlib.Path(output_dir)

    def export(
        self,
        database: Database,
        *,
        where: Mapping[str, Any] | None = None,
        memory_body: str | None = None,
        skills: dict[str, str] | None = None,
    ) -> ExportResult:
        """Render the (optionally scoped) store and write only changed artifacts.

        ``skills`` is the synthesized skill map (slug -> body) produced by
        :class:`~memu.memory_fs.synthesizer.MemorySynthesizer`; the ``skill/`` tree
        and its root ``SKILL.md`` index are sourced from it, never from memory items.
        ``memory_body`` is an optional synthesized override for the ``MEMORY.md``
        body; when omitted, ``MEMORY.md`` is rendered deterministically as an
        overview that links to the per-category ``memory/<slug>.md`` files. The
        ``resource/`` raw copies, ``memory/`` category files, and ``INDEX.md`` are
        always deterministic.
        """
        self.output_dir.mkdir(parents=True, exist_ok=True)
        scope = dict(where) if where else None

        categories = list(database.memory_category_repo.list_categories(where=scope).values())
        resources = list(database.resource_repo.list_resources(where=scope).values())

        # The shared trunk: one multimodal description per source file.
        descriptions = self._build_descriptions(resources)

        # resource/: copy the raw source bytes verbatim; ``links`` maps each
        # resource id to its relative path under resource/ for the INDEX.md links.
        raw_artifacts, links = self._resource_artifacts(descriptions)

        # memory/: one file per category, indexed by MEMORY.md.
        ordered_categories, category_slugs = self._category_slugs(categories)
        category_artifacts = {
            f"{MEMORY_DIRNAME}/{slug}.md": self._category_document(category)
            for category, slug in zip(ordered_categories, category_slugs, strict=True)
        }

        # The skill/ tree is a sibling bypass synthesized from the description
        # trunk (see MemorySynthesizer); ``skills`` is supplied by the caller.
        skill_map = skills or {}
        skill_artifacts = {
            f"{SKILL_DIRNAME}/{slug}/{SKILL_FILENAME}": self._skill_document(body) for slug, body in skill_map.items()
        }

        artifacts: dict[str, str | bytes] = {}
        artifacts.update(raw_artifacts)
        artifacts.update(category_artifacts)
        artifacts.update(skill_artifacts)
        if memory_body is not None:
            artifacts[MEMORY_FILENAME] = self._memory_document(memory_body)
        else:
            artifacts[MEMORY_FILENAME] = self._memory_index(ordered_categories, category_slugs)
        artifacts[INDEX_FILENAME] = self._index_bypass(descriptions, links)
        artifacts[SKILL_INDEX_FILENAME] = self._skill_index(skill_map)

        return self._sync(artifacts)

    # -- trunk -------------------------------------------------------------

    @staticmethod
    def _build_descriptions(resources: list[Resource]) -> list[FileDescription]:
        descriptions: list[FileDescription] = []
        for resource in sorted(resources, key=lambda r: (r.url, r.id)):
            descriptions.append(
                FileDescription(
                    url=resource.url,
                    modality=resource.modality,
                    description=" ".join((resource.caption or "").split()),
                    resource_id=resource.id,
                    local_path=resource.local_path,
                )
            )
        return descriptions

    @staticmethod
    def build_synthesis_descriptions(resources: list[Resource], items: list[MemoryItem]) -> list[FileDescription]:
        """Build synthesizer input from the structured store (extracted items).

        The synthesizer is fed the extracted memory items per source so that the
        structured store is the single source of truth for synthesis, rather than the
        lossy per-source caption. A source's caption is used only as a fallback when it
        has no extracted items yet (e.g. it failed extraction or has not been processed).
        """
        items_by_resource: dict[str, list[MemoryItem]] = {}
        for item in items:
            if item.resource_id:
                items_by_resource.setdefault(item.resource_id, []).append(item)

        descriptions: list[FileDescription] = []
        for resource in sorted(resources, key=lambda r: (r.url, r.id)):
            res_items = sorted(
                items_by_resource.get(resource.id, []),
                key=lambda i: (i.memory_type, i.created_at, i.id),
            )
            parts = [
                f"[{item.memory_type}] {' '.join((item.summary or '').split())}"
                for item in res_items
                if (item.summary or "").strip()
            ]
            description = "; ".join(parts) if parts else " ".join((resource.caption or "").split())
            descriptions.append(
                FileDescription(
                    url=resource.url,
                    modality=resource.modality,
                    description=description,
                    resource_id=resource.id,
                    local_path=resource.local_path,
                )
            )
        return descriptions

    # -- bypass: SKILL -----------------------------------------------------

    @staticmethod
    def _skill_document(body: str) -> str:
        return f"{_GENERATED_NOTICE}\n\n{body.strip()}\n"

    def _skill_index(self, skills: dict[str, str]) -> str:
        """A table of contents over the ``skill/`` tree (slug, description, link)."""
        lines = ["# Skills", "", _GENERATED_NOTICE, "", "## Skills", ""]
        if skills:
            for slug, body in sorted(skills.items()):
                description = self._skill_description(body) or "_No description._"
                link = f"{SKILL_DIRNAME}/{slug}/{SKILL_FILENAME}"
                lines.append(f"- [`{slug}`]({link}) — {description}")
        else:
            lines.append("_No skills yet._")
        lines.append("")
        return "\n".join(lines)

    @classmethod
    def _skill_description(cls, body: str) -> str:
        """A one-line description for the index: frontmatter ``description``/``name``.

        Falls back to the first non-empty, non-frontmatter line so a synthesized
        skill without explicit frontmatter still surfaces something readable.
        """
        lines = body.strip().splitlines()
        if lines and lines[0].strip() == "---":
            for line in lines[1:]:
                if line.strip() == "---":
                    break
                key, sep, value = line.partition(":")
                if sep and key.strip().lower() == "description" and value.strip():
                    return cls._inline(value.strip())
        for raw_line in lines:
            line = raw_line.strip()
            if not line or line == "---":
                continue
            return cls._inline(line.lstrip("#").strip())
        return ""

    # -- bypass: MEMORY ----------------------------------------------------

    @staticmethod
    def _memory_document(body: str) -> str:
        body = body.strip() or "_No memory yet._"
        return f"# Memory\n\n{_GENERATED_NOTICE}\n\n{body}\n"

    @staticmethod
    def _category_slugs(categories: list[MemoryCategory]) -> tuple[list[MemoryCategory], list[str]]:
        """Order categories deterministically and assign a unique slug to each.

        Returns the ordered categories alongside a parallel list of slugs (used for
        the ``memory/<slug>.md`` file names and the MEMORY.md links). Slug clashes
        are de-duplicated with a numeric suffix so files never collide.
        """
        ordered = sorted(categories, key=lambda c: (c.name.lower(), c.id))
        slugs: list[str] = []
        used: dict[str, int] = {}
        for category in ordered:
            base = slugify(category.name)
            count = used.get(base, 0)
            used[base] = count + 1
            slugs.append(base if count == 0 else f"{base}-{count + 1}")
        return ordered, slugs

    def _category_document(self, category: MemoryCategory) -> str:
        """A single ``memory/<slug>.md`` file: the category's description + summary."""
        description = self._inline((category.description or "").strip())
        summary = (category.summary or "").strip()
        lines = [f"# {category.name}", "", _GENERATED_NOTICE, ""]
        if description:
            lines.append(f"_{description}_")
            lines.append("")
        lines.append(summary or "_No summary yet._")
        lines.append("")
        return "\n".join(lines)

    def _memory_index(self, ordered: list[MemoryCategory], slugs: list[str]) -> str:
        """The deterministic ``MEMORY.md``: an overview linking to each category file."""
        lines = ["# Memory", "", _GENERATED_NOTICE, "", "## Overview", ""]
        if ordered:
            for category, slug in zip(ordered, slugs, strict=True):
                description = self._inline((category.description or "").strip())
                link = f"{MEMORY_DIRNAME}/{slug}.md"
                line = f"- [**{category.name}**]({link})"
                if description:
                    line = f"{line} — {description}"
                lines.append(line)
        else:
            lines.append("_No memory yet._")
        lines.append("")
        return "\n".join(lines)

    # -- bypass: RESOURCE + INDEX ------------------------------------------

    @staticmethod
    def _resource_artifacts(
        descriptions: list[FileDescription],
    ) -> tuple[dict[str, bytes], dict[str, str]]:
        """Copy each readable source file into ``resource/`` (verbatim bytes).

        Returns the ``resource/<name>`` -> raw bytes artifact map plus a
        ``resource_id`` -> relative path map used to link ``INDEX.md`` entries to
        their copies. Resources without a readable ``local_path`` are skipped (they
        are still listed in INDEX.md, just without a link). File-name collisions are
        de-duplicated with a numeric suffix so copies never clobber each other.
        """
        raw: dict[str, bytes] = {}
        links: dict[str, str] = {}
        used: dict[str, int] = {}
        for desc in descriptions:
            if not desc.local_path:
                continue
            path = pathlib.Path(desc.local_path)
            if not path.is_file():
                continue
            try:
                content = path.read_bytes()
            except OSError:
                continue
            name = desc.file_name
            count = used.get(name, 0)
            used[name] = count + 1
            out_name = name if count == 0 else MemoryFileExporter._suffix_name(name, count + 1)
            rel = f"{RESOURCE_DIRNAME}/{out_name}"
            raw[rel] = content
            links[desc.resource_id] = rel
        return raw, links

    @staticmethod
    def _suffix_name(name: str, n: int) -> str:
        """Insert a ``-n`` disambiguator before the extension (``a.txt`` -> ``a-2.txt``)."""
        stem, dot, ext = name.rpartition(".")
        if dot:
            return f"{stem}-{n}.{ext}"
        return f"{name}-{n}"

    def _index_bypass(self, descriptions: list[FileDescription], links: dict[str, str]) -> str:
        """An index of the raw source files copied into ``resource/``."""
        lines = ["# Index", "", _GENERATED_NOTICE, "", "## Files", ""]
        if descriptions:
            for desc in descriptions:
                text = desc.description or "_No description._"
                rel = links.get(desc.resource_id)
                label = f"[`{desc.file_name}`]({rel})" if rel else f"`{desc.file_name}`"
                lines.append(f"- {label} ({desc.modality}) — {text}")
        else:
            lines.append("_No source files yet._")
        lines.append("")
        return "\n".join(lines)

    # -- shared helpers ----------------------------------------------------

    @staticmethod
    def _inline(text: str) -> str:
        """Collapse a value to a single safe line."""
        return " ".join(text.split())

    # -- diff / write ------------------------------------------------------

    def _sync(self, artifacts: dict[str, str | bytes]) -> ExportResult:
        manifest = self._load_manifest()
        result = ExportResult(output_dir=str(self.output_dir))
        new_manifest: dict[str, str] = {}

        for rel_path, content in artifacts.items():
            digest = _content_hash(content)
            new_manifest[rel_path] = digest
            target = self.output_dir / rel_path
            if manifest.get(rel_path) == digest and target.exists():
                result.unchanged.append(rel_path)
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            if isinstance(content, bytes):
                target.write_bytes(content)
            else:
                target.write_text(content, encoding="utf-8")
            result.written.append(rel_path)

        for rel_path in manifest:
            if rel_path in new_manifest:
                continue
            stale = self.output_dir / rel_path
            if stale.exists():
                stale.unlink()
            self._prune_empty_dirs(stale.parent)
            result.removed.append(rel_path)

        self._save_manifest(new_manifest)
        return result

    def _prune_empty_dirs(self, directory: pathlib.Path) -> None:
        """Remove now-empty directories created for nested artifacts (e.g. skill/<name>)."""
        root = self.output_dir.resolve()
        current = directory
        while current.resolve() != root and root in current.resolve().parents:
            try:
                next(current.iterdir())
            except StopIteration:
                current.rmdir()
                current = current.parent
            except OSError:
                break
            else:
                break

    # -- reading existing artifacts (for incremental update) ---------------

    def artifacts_exist(self) -> bool:
        """Whether a prior memory tree is already present (init vs update)."""
        return (self.output_dir / MEMORY_FILENAME).exists()

    def read_memory_body(self) -> str:
        """Read MEMORY.md and strip the heading/notice, returning just the body."""
        path = self.output_dir / MEMORY_FILENAME
        if not path.exists():
            return ""
        return self._strip_chrome(path.read_text(encoding="utf-8"), drop_heading="# Memory")

    def read_skills(self) -> dict[str, str]:
        """Read existing ``skill/<slug>/SKILL.md`` bodies keyed by slug."""
        skills: dict[str, str] = {}
        skill_root = self.output_dir / SKILL_DIRNAME
        if not skill_root.is_dir():
            return skills
        for child in sorted(skill_root.iterdir()):
            doc = child / SKILL_FILENAME
            if child.is_dir() and doc.exists():
                skills[child.name] = self._strip_chrome(doc.read_text(encoding="utf-8"))
        return skills

    @staticmethod
    def _strip_chrome(text: str, *, drop_heading: str | None = None) -> str:
        lines = text.splitlines()
        kept = [
            line
            for line in lines
            if line.strip() != _GENERATED_NOTICE and (drop_heading is None or line.strip() != drop_heading)
        ]
        return "\n".join(kept).strip()

    def _load_manifest(self) -> dict[str, str]:
        manifest_path = self.output_dir / MANIFEST_NAME
        if not manifest_path.exists():
            return {}
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
        if not isinstance(data, dict):
            return {}
        return {str(key): str(value) for key, value in data.items()}

    def _save_manifest(self, manifest: dict[str, str]) -> None:
        manifest_path = self.output_dir / MANIFEST_NAME
        manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")


__all__ = ["ExportResult", "FileDescription", "MemoryFileExporter", "slugify"]
