name: 17. Docs

on:
  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/_docs.yml'
      - '.github/workflows/_docs-deploy.yml'
      - '.github/workflows/docs.yml'
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - '.github/workflows/_docs.yml'
      - '.github/workflows/_docs-deploy.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docs-check:
    name: Build Docs
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/_docs.yml
    permissions:
      contents: read

  docs-deploy:
    name: Build and Deploy Docs
    if: github.repository == 'volcengine/OpenViking' && github.event_name != 'pull_request'
    uses: ./.github/workflows/_docs-deploy.yml
    permissions:
      contents: read
      pages: write
      id-token: write
