/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as SessionsRouteRouteImport } from './routes/sessions/route'
import { Route as RetrievalRouteRouteImport } from './routes/retrieval/route'
import { Route as RequestLogsRouteRouteImport } from './routes/request-logs/route'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as HomeRouteRouteImport } from './routes/home/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as OauthVerifyRouteImport } from './routes/oauth/verify'
import { Route as OauthConsentRouteImport } from './routes/oauth/consent'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRouteRoute = SessionsRouteRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RetrievalRouteRoute = RetrievalRouteRouteImport.update({
  id: '/retrieval',
  path: '/retrieval',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestLogsRouteRoute = RequestLogsRouteRouteImport.update({
  id: '/request-logs',
  path: '/request-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRouteRoute = HomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SessionsRouteRoute,
} as any)
const OauthVerifyRoute = OauthVerifyRouteImport.update({
  id: '/oauth/verify',
  path: '/oauth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/settings': typeof SettingsRouteRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/sessions': typeof SessionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRouteRoute
  '/playground': typeof PlaygroundRouteRoute
  '/request-logs': typeof RequestLogsRouteRoute
  '/retrieval': typeof RetrievalRouteRoute
  '/sessions': typeof SessionsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/oauth/verify': typeof OauthVerifyRoute
  '/sessions/': typeof SessionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/playground'
    | '/request-logs'
    | '/retrieval'
    | '/sessions'
    | '/settings'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/sessions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/playground'
    | '/request-logs'
    | '/retrieval'
    | '/settings'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/sessions'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/playground'
    | '/request-logs'
    | '/retrieval'
    | '/sessions'
    | '/settings'
    | '/oauth/consent'
    | '/oauth/verify'
    | '/sessions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRouteRoute: typeof HomeRouteRoute
  PlaygroundRouteRoute: typeof PlaygroundRouteRoute
  RequestLogsRouteRoute: typeof RequestLogsRouteRoute
  RetrievalRouteRoute: typeof RetrievalRouteRoute
  SessionsRouteRoute: typeof SessionsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRoute
  OauthConsentRoute: typeof OauthConsentRoute
  OauthVerifyRoute: typeof OauthVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retrieval': {
      id: '/retrieval'
      path: '/retrieval'
      fullPath: '/retrieval'
      preLoaderRoute: typeof RetrievalRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-logs': {
      id: '/request-logs'
      path: '/request-logs'
      fullPath: '/request-logs'
      preLoaderRoute: typeof RequestLogsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof SessionsRouteRoute
    }
    '/oauth/verify': {
      id: '/oauth/verify'
      path: '/oauth/verify'
      fullPath: '/oauth/verify'
      preLoaderRoute: typeof OauthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SessionsRouteRouteChildren {
  SessionsIndexRoute: typeof SessionsIndexRoute
}

const SessionsRouteRouteChildren: SessionsRouteRouteChildren = {
  SessionsIndexRoute: SessionsIndexRoute,
}

const SessionsRouteRouteWithChildren = SessionsRouteRoute._addFileChildren(
  SessionsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRouteRoute: HomeRouteRoute,
  PlaygroundRouteRoute: PlaygroundRouteRoute,
  RequestLogsRouteRoute: RequestLogsRouteRoute,
  RetrievalRouteRoute: RetrievalRouteRoute,
  SessionsRouteRoute: SessionsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRoute,
  OauthConsentRoute: OauthConsentRoute,
  OauthVerifyRoute: OauthVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
